#!/bin/bash
sudo apt-get update
sudo apt-get install -y git mercurial subversion fossil bzr lftp
rm -fr virtualenv .tox
virtualenv --python=python3 virtualenv
source virtualenv/bin/activate
pip install -r requirements.txt
pip install -e .
