# -*- coding: utf-8 -*-
"""
This family file was auto-generated by
$Id: 5505b6946288526e308aabb0759a14629a9f4ed9 $
Configuration parameters:
  url = http://directory.fsf.org/wiki/Main_Page
  name = fsd

Please do not commit this to the Git repository!
"""

from pywikibot import family
from pywikibot.tools import deprecated


class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'fsd'
        self.langs = {
            'en': 'directory.fsf.org',
        }

    def scriptpath(self, code):
        return {
            'en': '/w',
        }[code]

    @deprecated('APISite.version()')
    def version(self, code):
        return {
            'en': u'1.20.2',
        }[code]

    def protocol(self, code):
        return {
            'en': u'http',
        }[code]
